apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-sys
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prd/sys
    repoURL: https://github.com/gitops-demo/cd-manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
