apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-a
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: app
  source:
    helm:
      valueFiles:
      - values/dev-app-a.yaml
    path: app-a
    repoURL: https://github.com/gitops-demo/manifests
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
