apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: sys
  source:
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/gitops-demo/system-manifests/prd/kube-system/sealed-secrets/values/prd-sealed-secrets.yaml
    path: stable/sealed-secrets
    repoURL: https://github.com/helm/charts
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
